### ISSUE TITLE
[Improvement] Using while-loop or for-loop instead of map/range to improve performance

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2071]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

org.apache.kyuubi.engine.spark.schema.RowSet#toColumnBasedSet
org.apache.kyuubi.engine.spark.schema.RowSet#toRowBasedSet

for example, we can prevent creating range objects, like, (0 until row.length)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
Hi @zhaomin1423, would you like to check on this?

**Comment by cfmcgrady** [comment]
FYI: https://github.com/databricks/scala-style-guide#traversal-and-zipwithindex

**Comment by yaooqinn** [comment]
Maybe we shall introduce the db guide in our code repo in CONTRIBUTING.md

**Comment by zhaomin1423** [comment]
Yes, of course



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Kent ***@***.***> |
| 日期 | 2022年03月09日 14:28 |
| 收件人 | ***@***.***> |
| 抄送至 | Xiao ***@***.******@***.***> |
| 主题 | Re: [apache/incubator-kyuubi] [Improvement] Using while-loop or for-loop instead of map/range to improve performance (Issue #2071) |

Hi @zhaomin1423, would you like to check on this?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ulysses-you** [comment]
+1

**Comment by zhaomin1423** [comment]
Would we do this improve in the whole project, or part of the module？

**Comment by yaooqinn** [comment]
> Would we do this improve in the whole project, or part of the module？

one by one、I don't know whether other modules have same problem either
