### ISSUE TITLE
[Umbrella] Add Z-Order extensions to optimize table with zorder

### ISSUE THREAD

**Issue by qphien** [apache/incubator-kyuubi#939]
# Describe the proposal
To perform highly selective file pruning and make queries more efficient, files must be mutually exclusive in their data. Z-order  is a popular data skipping technique using in a variety of RDBMS systems as well as cloud based databases to enhance query efficiency with complex filters.

databricks docs:
https://docs.databricks.com/spark/2.x/spark-sql/language-manual/optimize.html

## zorder work
There is some work to do with zorder:

- Support SQL: `OPTIMIZE <table> [WHERE <predicate>] ZORDER BY (col1, col2, ...)`
   Optimize data matching the given partition predicate. `WHERE` clause only supports partition filters.
- Support SQL: `CREATE <table> ... ZORDER BY (col1, col2, ...)`
   Data will be sorted by zorder automatically before writing to zorder table.

## about test 
See the picture, the SQL extension test coverage is less than other module.
![image](https://user-images.githubusercontent.com/12025282/132435246-51404158-820b-4e34-9a4e-1ec778a07950.png)

# Task list

- #990
- #1045 
- #1055
- #1070
- #1157

**Comment by yaooqinn** [comment]
Awsome!

**Comment by ulysses-you** [comment]
To developers:

We merged zorder https://github.com/apache/incubator-kyuubi/pull/990 into master branch (for 1.4.0) recently. There are still many things can be done for the zorder and the test.

# zorder work

- support more relation (only `HiveTableRelation` for now)
- support more table format, since Spark doesn't support insert overwrite and read the same datasource table
- support optimzie zorder through tbl properteis; I think @qphien is working on this
- zorder expression with codegen
- zorder docs
- beanchmark of zorder for write side
- beanchmark of zorder for read side
- etc ...

# test coverage
we only have the end-end test of zorder, . as far as I know, we need more test include:

- unit test of analyzed zorder plan
- test different column data type
- test different partition data type
- test different table format
- etc ...

I wonder If you are interested in this feature. Look forward to your idea. @qphien  @cfmcgrady @hzxiongyinke @timothy65535 @hddong @zhaomin1423

**Comment by PengleiShi** [comment]
hi @ulysses-you , about supporting insert overwrite and read the same datasource table, now it's ok for dynamic partition insert when `PartitionOverwriteMode` is `DYNAMIC`, but it not works for static partition insert. I think there is a easy way to support static partition insert https://github.com/apache/spark/pull/34141/files，What is the community's plan？

**Comment by ulysses-you** [comment]
hi @PengleiShi , this issue seems not about Apache Kyuubi, so I can not talk more. You can ask the related expert in Apache Spark community.
